---
id: Crypt
name: Crypt
full: Cryptography library
description: A library that provides wrappers for various cryptographic systems.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Crypt
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha5
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
      horde/http: ^3
      horde/mime: ^3
      horde/stream: ^2
      horde/stream_filter: ^3
      horde/translation: ^3
      horde/url: ^3
      horde/util: ^3
    ext:
      hash: '*'
      openssl: '*'
  optional:
    composer:
      horde/test: ^3
